import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import flagImage from "../../public/images/flag-rio-preto.png";
import { Button } from "primereact/button";
import { Checkbox } from "primereact/checkbox";
import { Chips } from "primereact/chips";
import { InputText } from "primereact/inputtext";
import { useState } from "react";

const Home: NextPage = () => {
  const [checked, setChecked] = useState(false);
  const [keywords, setKeywords] = useState<string[]>([]);

  const handleKeywordsChange = (values: string[]) =>
    setKeywords(values.map((v) => v.toLocaleLowerCase()));

  const handleSubscribeClick = () => {
    console.log("handleSubscribeClick");
  };

  const head = () => (
    <Head>
      <title>Boletim Diário - Rio Preto</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );

  const hero = () => (
    <div className="grid grid-nogutter surface-0 text-800">
      <div className="col-12 md:col-6 p-6 text-center md:text-left flex align-items-center ">
        <section>
          <div className="block text-5xl font-bold mb-1">
            Boletim Diário - Rio Preto
          </div>
          <p className="mt-0 mb-4 text-700 line-height-3">
            Receba em seu e-mail todas as publicações importantes do Diário
            Oficial!
          </p>

          <Button
            label="Inscreva-se"
            type="button"
            className="mr-3 p-button-raised"
          />
        </section>
      </div>
      <div className="hidden md:inline-block md:col-6 overflow-hidden">
        <figure
          style={{ clipPath: "polygon(8% 0, 100% 0%, 100% 100%, 0 100%)" }}
        >
          <Image src={flagImage} alt="Bandeira de São José do Rio Preto-SP" />
        </figure>
      </div>
    </div>
  );

  const feature = () => (
    <section>
      <div className="surface-0 text-center">
        <div className="mb-3 font-bold text-2xl">
          <h2 className="text-900">Um boletim, muitas funcionalidades!</h2>
        </div>
        <div className="grid">
          <div className="col-12 md:col-4 mb-4 px-5">
            <span
              className="p-3 shadow-2 mb-3 inline-block"
              style={{ borderRadius: "10px" }}
            >
              <i className="pi pi-check-circle text-4xl text-blue-500"></i>
            </span>
            <div className="text-900 mb-3 font-medium">Fácil de usar</div>
            <span className="text-700 text-sm line-height-3">
              É só cadastrar, confirmar seu e-mail e pronto! Você já começa a
              receber as publicações diariamente!
            </span>
          </div>
          <div className="col-12 md:col-4 mb-4 px-5">
            <span
              className="p-3 shadow-2 mb-3 inline-block"
              style={{ borderRadius: "10px" }}
            >
              <i className="pi pi-lock text-4xl text-blue-500"></i>
            </span>
            <div className="text-900 mb-3 font-medium">Privacidade</div>
            <span className="text-700 text-sm line-height-3">
              Seu e-mail é criptografado em padrão avançado (AES) com chave de
              128 bits, um dos padrões mais seguros da atualidade.
            </span>
          </div>
          <div className="col-12 md:col-4 mb-4 px-5">
            <span
              className="p-3 shadow-2 mb-3 inline-block"
              style={{ borderRadius: "10px" }}
            >
              <i className="pi pi-clock text-4xl text-blue-500"></i>
            </span>
            <div className="text-900 mb-3 font-medium">Economia de tempo</div>
            <span className="text-700 text-sm line-height-3">
              Pesquisaremos diariamente as publicações do diário oficial de
              acordo com as palavras-chave que você desejar.
            </span>
          </div>
          <div className="col-12 md:col-4 mb-4 px-5">
            <span
              className="p-3 shadow-2 mb-3 inline-block"
              style={{ borderRadius: "10px" }}
            >
              <i className="pi pi-globe text-4xl text-blue-500"></i>
            </span>
            <div className="text-900 mb-3 font-medium">Economia de dados</div>
            <span className="text-700 text-sm line-height-3">
              Os e-mails enviados não contêm arquivos anexos, mas apenas o link
              das publicações, economizando espaço na sua caixa de entrada.
            </span>
          </div>
          <div className="col-12 md:col-4 md:mb-4 mb-0 px-3">
            <span
              className="p-3 shadow-2 mb-3 inline-block"
              style={{ borderRadius: "10px" }}
            >
              <i className="pi pi-shield text-4xl text-blue-500"></i>
            </span>
            <div className="text-900 mb-3 font-medium">Segurança</div>
            <span className="text-700 text-sm line-height-3">
              Nossos e-mails não possuem anexos e os links das publicações levam
              direto ao site do Diário Oficial, portanto não há riscos de vírus
              e outras ameaças.
            </span>
          </div>
          <div className="col-12 md:col-4 mb-4 px-5">
            <span
              className="p-3 shadow-2 mb-3 inline-block"
              style={{ borderRadius: "10px" }}
            >
              <i className="pi pi-github text-4xl text-blue-500"></i>
            </span>
            <div className="text-900 mb-3 font-medium">Código aberto</div>
            <span className="text-700 text-sm line-height-3">
              O código-fonte da nossa plataforma é totalmente aberto e está
              disponível no Github.
            </span>
          </div>
        </div>
      </div>
    </section>
  );

  const stats = () => (
    <section>
      <h3 className="text-center">Nossos números</h3>
      <div className="grid">
        <div className="col-12 md:col-6 lg:col-3">
          <div className="surface-0 shadow-2 p-3 border-1 border-50 border-round">
            <div className="flex justify-content-between mb-3">
              <div>
                <span className="block text-500 font-medium mb-3">
                  Inscritos
                </span>
                <div className="text-900 font-medium text-xl">152</div>
              </div>
              <div
                className="flex align-items-center justify-content-center bg-blue-100 border-round"
                style={{ width: "2.5rem", height: "2.5rem" }}
              >
                <i className="pi pi-shopping-cart text-blue-500 text-xl"></i>
              </div>
            </div>
            <span className="text-green-500 font-medium">24 new </span>
            <span className="text-500">since last visit</span>
          </div>
        </div>
        <div className="col-12 md:col-6 lg:col-3">
          <div className="surface-0 shadow-2 p-3 border-1 border-50 border-round">
            <div className="flex justify-content-between mb-3">
              <div>
                <span className="block text-500 font-medium mb-3">
                  Palavras-chave cadastradas
                </span>
                <div className="text-900 font-medium text-xl">$2.100</div>
              </div>
              <div
                className="flex align-items-center justify-content-center bg-orange-100 border-round"
                style={{ width: "2.5rem", height: "2.5rem" }}
              >
                <i className="pi pi-map-marker text-orange-500 text-xl"></i>
              </div>
            </div>
            <span className="text-green-500 font-medium">%52+ </span>
            <span className="text-500">since last week</span>
          </div>
        </div>
        <div className="col-12 md:col-6 lg:col-3">
          <div className="surface-0 shadow-2 p-3 border-1 border-50 border-round">
            <div className="flex justify-content-between mb-3">
              <div>
                <span className="block text-500 font-medium mb-3">
                  Emails enviados
                </span>
                <div className="text-900 font-medium text-xl">28441</div>
              </div>
              <div
                className="flex align-items-center justify-content-center bg-cyan-100 border-round"
                style={{ width: "2.5rem", height: "2.5rem" }}
              >
                <i className="pi pi-inbox text-cyan-500 text-xl"></i>
              </div>
            </div>
            <span className="text-green-500 font-medium">520 </span>
            <span className="text-500">newly registered</span>
          </div>
        </div>
        <div className="col-12 md:col-6 lg:col-3">
          <div className="surface-0 shadow-2 p-3 border-1 border-50 border-round">
            <div className="flex justify-content-between mb-3">
              <div>
                <span className="block text-500 font-medium mb-3">
                  Comments
                </span>
                <div className="text-900 font-medium text-xl">152 Unread</div>
              </div>
              <div
                className="flex align-items-center justify-content-center bg-purple-100 border-round"
                style={{ width: "2.5rem", height: "2.5rem" }}
              >
                <i className="pi pi-comment text-purple-500 text-xl"></i>
              </div>
            </div>
            <span className="text-green-500 font-medium">85 </span>
            <span className="text-500">responded</span>
          </div>
        </div>
      </div>
    </section>
  );
  return (
    <div>
      {head()}
      {hero()}
      {feature()}
      {/* {stats()} */}
      <main>
        <div className="flex align-items-center justify-content-center">
          <div className="surface-card p-4 shadow-2 border-round w-full lg:w-6 p-fluid">
            <div className="surface-0 text-700 text-center">
              <div className="text-900 font-bold text-5xl mb-3">
                Inscreva-se gratuitamente!
              </div>
              <div className="text-700 text-2xl mb-5">
                Digite seu e-mail e as palavras-chaves desejadas.
              </div>
            </div>

            <div>
              <label
                htmlFor="email"
                className="block text-900 font-medium mb-2"
              >
                Email
              </label>
              <InputText id="email" type="text" className="w-full mb-3" />

              <div className="flex align-items-center justify-content-between mb-6">
                <div className="flex align-items-center">
                  <Checkbox
                    id="all-keywords"
                    onChange={(e) => setChecked(e.checked)}
                    checked={checked}
                    className="mr-2"
                  />
                  <label htmlFor="all-keywords">Todas as publicações</label>
                </div>
              </div>

              {!checked && (
                <>
                  <label
                    htmlFor="keywords"
                    className="block text-900 font-medium mb-2"
                  >
                    Palavras-chave
                  </label>
                  <Chips
                    id="keywords"
                    separator=","
                    allowDuplicate={false}
                    readOnly={checked}
                    disabled={checked}
                    value={keywords}
                    onChange={(e) => handleKeywordsChange(e.value)}
                    className="w-full mb-3"
                  />
                </>
              )}

              <Button
                label="Enviar"
                icon="pi pi-envelope"
                className="w-full"
                onClick={handleSubscribeClick}
              />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
};

export default Home;
