import type { ReactElement } from "react";
import Head from "next/head";
import Footer from "./footer";
import Header from "./header";
import styles from "../styles/Layout.module.css";

export default function Layout({ children }: { children: ReactElement }) {
  return (
    <>
      <Head>
        <title>Boletim Diário - Rio Preto</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.container}>
        <Header />
        {children}
        <Footer />
      </div>
    </>
  );
}
